upload:
  root-path: D:/nginx-1.28.1/html/
  admin-head-path: house/adminHeadPic/
  book-pic-path: house/housePic/
server:
  port: 8080
  servlet:
    context-path:
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fs?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: root
    password: 852085
# 注释掉原来的 mybatis 配置，改为 mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 其他原有 mybatis 配置也移到 mybatis-plus 下
  type-aliases-package: com.jinsi.housedemo.entity
  mapper-locations: classpath:mapper/*.xml